[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/sync"
  [headers.values]
    Cache-Control = "no-store"
